@ECHO OFF

REM gracethdcheck_pg_export_csv_anom.bat
REM Owner : GraceTHD-Community - http://gracethd-community.github.io/
REM Author : stephane dot byache at aleno dot eu
REM Rev. date : 17/02/2017

    REM This file is part of GraceTHD.

    REM GraceTHD is free software: you can redistribute it and/or modify
    REM it under the terms of the GNU General Public License as published by
    REM the Free Software Foundation, either version 3 of the License, or
    REM (at your option) any later version.

    REM GraceTHD is distributed in the hope that it will be useful,
    REM but WITHOUT ANY WARRANTY; without even the implied warranty of
    REM MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    REM GNU General Public License for more details.

    REM You should have received a copy of the GNU General Public License
    REM along with GraceTHD.  If not, see <http://www.gnu.org/licenses/>.


REM TODO: CREATION DES DOSSIERS SI NON EXISTANTS ? A TESTER pg_EXPORT
REM TODO: mettre dans un dossier check\pg pour éviter d'écraser avec Spatialite ou autre. 

CALL config.bat

REM Decommenter quand ca coince. 
REM CALL:DEBUG

REM Pour Postgis, GLCTCONF correspond a GLPGCONFPATH pour le cas ou GLPGCONFPATH serait different de GLCTCONF (pb de droits d'acces). 
SET GLCTCONF=%GLPGCONFPATH%

CALL :CT01
CALL :CT02
CALL :CT03
CALL :CT04
CALL :CT06
CALL :CT07
CALL :CT09
CALL :END


:CT01
SET GLPGV=v_ct_anom_1_pre
SET GLPGCSVTBL=%GLCTPGSCHEMACHECK%.%GLPGV%
SET GLPGCSV=%GLPGCHECKPATH%\postgis\%GLPGV%.csv
ECHO GRACETHD-CHECK - DEBUT EXPORT %GLPGCSVTBL%
"%GL_PSQL%" -h %PGHOSTNAME% -p %PGPORT% -c "\COPY (SELECT * FROM %GLPGCSVTBL%) TO '%GLPGCSV%' %PGCSVCONF%;" -d %GLCTPGDB% %PGUSER%
ECHO GRACETHD-CHECK - FIN EXPORT %GLPGCSVTBL%

GOTO:EOF

:CT02
SET GLPGV=v_ct_anom_2_dia
SET GLPGCSVTBL=%GLCTPGSCHEMACHECK%.%GLPGV%
SET GLPGCSV=%GLPGCHECKPATH%\postgis\%GLPGV%.csv
ECHO GRACETHD-CHECK - DEBUT EXPORT %GLPGCSVTBL%
"%GL_PSQL%" -h %PGHOSTNAME% -p %PGPORT% -c "\COPY (SELECT * FROM %GLPGCSVTBL%) TO '%GLPGCSV%' %PGCSVCONF%;" -d %GLCTPGDB% %PGUSER%
ECHO GRACETHD-CHECK - FIN EXPORT %GLPGCSVTBL%

GOTO:EOF

:CT03
SET GLPGV=v_ct_anom_3_avp
SET GLPGCSVTBL=%GLCTPGSCHEMACHECK%.%GLPGV%
SET GLPGCSV=%GLPGCHECKPATH%\postgis\%GLPGV%.csv
ECHO GRACETHD-CHECK - DEBUT EXPORT %GLPGCSVTBL%
"%GL_PSQL%" -h %PGHOSTNAME% -p %PGPORT% -c "\COPY (SELECT * FROM %GLPGCSVTBL%) TO '%GLPGCSV%' %PGCSVCONF%;" -d %GLCTPGDB% %PGUSER%
ECHO GRACETHD-CHECK - FIN EXPORT %GLPGCSVTBL%

GOTO:EOF

:CT04
SET GLPGV=v_ct_anom_4_pro
SET GLPGCSVTBL=%GLCTPGSCHEMACHECK%.%GLPGV%
SET GLPGCSV=%GLPGCHECKPATH%\postgis\%GLPGV%.csv
ECHO GRACETHD-CHECK - DEBUT EXPORT %GLPGCSVTBL%
"%GL_PSQL%" -h %PGHOSTNAME% -p %PGPORT% -c "\COPY (SELECT * FROM %GLPGCSVTBL%) TO '%GLPGCSV%' %PGCSVCONF%;" -d %GLCTPGDB% %PGUSER%
ECHO GRACETHD-CHECK - FIN EXPORT %GLPGCSVTBL%

GOTO:EOF

:CT05
SET GLPGV=v_ct_anom_5_act
SET GLPGCSVTBL=%GLCTPGSCHEMACHECK%.%GLPGV%
SET GLPGCSV=%GLPGCHECKPATH%\postgis\%GLPGV%.csv
ECHO GRACETHD-CHECK - DEBUT EXPORT %GLPGCSVTBL%
"%GL_PSQL%" -h %PGHOSTNAME% -p %PGPORT% -c "\COPY (SELECT * FROM %GLPGCSVTBL%) TO '%GLPGCSV%' %PGCSVCONF%;" -d %GLCTPGDB% %PGUSER%
ECHO GRACETHD-CHECK - FIN EXPORT %GLPGCSVTBL%

GOTO:EOF


:CT06
SET GLPGV=v_ct_anom_6_exe
SET GLPGCSVTBL=%GLCTPGSCHEMACHECK%.%GLPGV%
SET GLPGCSV=%GLPGCHECKPATH%\postgis\%GLPGV%.csv
ECHO GRACETHD-CHECK - DEBUT EXPORT %GLPGCSVTBL%
"%GL_PSQL%" -h %PGHOSTNAME% -p %PGPORT% -c "\COPY (SELECT * FROM %GLPGCSVTBL%) TO '%GLPGCSV%' %PGCSVCONF%;" -d %GLCTPGDB% %PGUSER%
ECHO GRACETHD-CHECK - FIN EXPORT %GLPGCSVTBL%

GOTO:EOF

:CT07
SET GLPGV=v_ct_anom_7_tvx_ou_rec
SET GLPGCSVTBL=%GLCTPGSCHEMACHECK%.%GLPGV%
SET GLPGCSV=%GLPGCHECKPATH%\postgis\%GLPGV%.csv
ECHO GRACETHD-CHECK - DEBUT EXPORT %GLPGCSVTBL%
"%GL_PSQL%" -h %PGHOSTNAME% -p %PGPORT% -c "\COPY (SELECT * FROM %GLPGCSVTBL%) TO '%GLPGCSV%' %PGCSVCONF%;" -d %GLCTPGDB% %PGUSER%
ECHO GRACETHD-CHECK - FIN EXPORT %GLPGCSVTBL%

GOTO:EOF

:CT08
SET GLPGV=v_ct_anom_8_rec
SET GLPGCSVTBL=%GLCTPGSCHEMACHECK%.%GLPGV%
SET GLPGCSV=%GLPGCHECKPATH%\postgis\%GLPGV%.csv
ECHO GRACETHD-CHECK - DEBUT EXPORT %GLPGCSVTBL%
"%GL_PSQL%" -h %PGHOSTNAME% -p %PGPORT% -c "\COPY (SELECT * FROM %GLPGCSVTBL%) TO '%GLPGCSV%' %PGCSVCONF%;" -d %GLCTPGDB% %PGUSER%
ECHO GRACETHD-CHECK - FIN EXPORT %GLPGCSVTBL%

GOTO:EOF


:CT09
SET GLPGV=v_ct_anom_9_mco
SET GLPGCSVTBL=%GLCTPGSCHEMACHECK%.%GLPGV%
SET GLPGCSV=%GLPGCHECKPATH%\postgis\%GLPGV%.csv
ECHO GRACETHD-CHECK - DEBUT EXPORT %GLPGCSVTBL%
"%GL_PSQL%" -h %PGHOSTNAME% -p %PGPORT% -c "\COPY (SELECT * FROM %GLPGCSVTBL%) TO '%GLPGCSV%' %PGCSVCONF%;" -d %GLCTPGDB% %PGUSER%
ECHO GRACETHD-CHECK - FIN EXPORT %GLPGCSVTBL%

:END
ECHO GraceTHD - Postgis - Fin de creation de la base de donnees %PGHOSTNAME%:%GLCTPGDB%. 

%GLPAUSE%
EXIT
