@ECHO OFF

REM TODO: Appel 2 fois :LAUNCH. 
REM Une fois pour le template, une fois pour shpcsv-in
ECHO NE FONCTIONNE PAS !! ARRETER CE SCRIPT. 
PAUSE

:LAUNCH
CALL:CONFIG
REM SHPCSV-IN
SET 
CALL:CONNECTSHP
PAUSE
CALL:CONNECTCSV
PAUSE

REM SHPCSV-template
SET 
CALL:CONNECTSHP
CALL:CONNECTCSV



GOTO:EOF

:CONFIG
CALL config.bat

REM :VARIABLES
REM SET GLSPLEX=spatialite.exe --silent
REM SET GLCTDBSPL=.\dbinteg\gracelite_integ.sqlite
REM SET GLSHPINPATH=.\shpcsv-in\
REM SET GLCTDBSPLSCHEMA=.\sql_spatialite\
REM SET GLSHPINCODE=CP1252
REM SET GLSHPINSRID=2154
REM SET GLCSVINCODE=UTF-8
REM REM SET CODECSV=CP1252
REM SET GLCSVINQUOTE=NONE
REM SET GLCSVINDELIM=;

GOTO:EOF

:CONNECTSHP
ECHO DEBUT DE CONNEXION DES SHAPEFILES (TABLES vt_)
REM %GLSPLEX% "%GLCTDBSPL%" "CREATE VIRTUAL TABLE 'vt_shpsupport' USING VirtualShape('%GLSHPINPATH%Les supports', 'CP1252', 2154);"

SET SHP=t_adresse
SET SPLVT=vt_adresse
SET SPLSQL="CREATE VIRTUAL TABLE '%SPLVT%' USING VirtualShape('%GLSHPINPATH%\%SHP%', '%GLSHPINCODE%', %GLSHPINSRID%);"
IF EXIST "%GLSHPINPATH%\%SHP%.shp" %GLSPLEX% "%GLCTDBSPL%" %SPLSQL%

SET SHP=t_noeud
SET SPLVT=vt_noeud
SET SPLSQL="CREATE VIRTUAL TABLE '%SPLVT%' USING VirtualShape('%GLSHPINPATH%\%SHP%', '%GLSHPINCODE%', %GLSHPINSRID%);"
IF EXIST "%GLSHPINPATH%\%SHP%.shp" %GLSPLEX% "%GLCTDBSPL%" %SPLSQL%

SET SHP=t_cheminement
SET SPLVT=vt_cheminement
SET SPLSQL="CREATE VIRTUAL TABLE '%SPLVT%' USING VirtualShape('%GLSHPINPATH%\%SHP%', '%GLSHPINCODE%', %GLSHPINSRID%);"
IF EXIST "%GLSHPINPATH%\%SHP%.shp" %GLSPLEX% "%GLCTDBSPL%" %SPLSQL%

SET SHP=t_cable
SET SPLVT=vt_cable
SET SPLSQL="CREATE VIRTUAL TABLE '%SPLVT%' USING VirtualShape('%GLSHPINPATH%\%SHP%', '%GLSHPINCODE%', %GLSHPINSRID%);"
IF EXIST "%GLSHPINPATH%\%SHP%.shp" %GLSPLEX% "%GLCTDBSPL%" %SPLSQL%

SET SHP=t_znro
SET SPLVT=vt_znro
SET SPLSQL="CREATE VIRTUAL TABLE '%SPLVT%' USING VirtualShape('%GLSHPINPATH%\%SHP%', '%GLSHPINCODE%', %GLSHPINSRID%);"
IF EXIST "%GLSHPINPATH%\%SHP%.shp" %GLSPLEX% "%GLCTDBSPL%" %SPLSQL%

SET SHP=t_zsro
SET SPLVT=vt_zsro
SET SPLSQL="CREATE VIRTUAL TABLE '%SPLVT%' USING VirtualShape('%GLSHPINPATH%\%SHP%', '%GLSHPINCODE%', %GLSHPINSRID%);"
IF EXIST "%GLSHPINPATH%\%SHP%.shp" %GLSPLEX% "%GLCTDBSPL%" %SPLSQL%

SET SHP=t_zpbo
SET SPLVT=vt_zpbo
SET SPLSQL="CREATE VIRTUAL TABLE '%SPLVT%' USING VirtualShape('%GLSHPINPATH%\%SHP%', '%GLSHPINCODE%', %GLSHPINSRID%);"
IF EXIST "%GLSHPINPATH%\%SHP%.shp" %GLSPLEX% "%GLCTDBSPL%" %SPLSQL%

SET SHP=t_zdep
SET SPLVT=vt_zdep
SET SPLSQL="CREATE VIRTUAL TABLE '%SPLVT%' USING VirtualShape('%GLSHPINPATH%\%SHP%', '%GLSHPINCODE%', %GLSHPINSRID%);"
IF EXIST "%GLSHPINPATH%\%SHP%.shp" %GLSPLEX% "%GLCTDBSPL%" %SPLSQL%

SET SHP=t_zcoax
SET SPLVT=vt_zcoax
SET SPLSQL="CREATE VIRTUAL TABLE '%SPLVT%' USING VirtualShape('%GLSHPINPATH%\%SHP%', '%GLSHPINCODE%', %GLSHPINSRID%);"
IF EXIST "%GLSHPINPATH%\%SHP%.shp" %GLSPLEX% "%GLCTDBSPL%" %SPLSQL%

SET SHP=t_empreinte
SET SPLVT=vt_empreinte
SET SPLSQL="CREATE VIRTUAL TABLE '%SPLVT%' USING VirtualShape('%GLSHPINPATH%\%SHP%', '%GLSHPINCODE%', %GLSHPINSRID%);"
IF EXIST "%GLSHPINPATH%\%SHP%.shp" %GLSPLEX% "%GLCTDBSPL%" %SPLSQL%

ECHO FIN DE CONNEXION DES SHAPEFILES (TABLES vt_)

GOTO:EOF

:CONNECTCSV
ECHO DEBUT DE CONNEXION DES CSV (TABLES vt_)

SET CSV=t_organisme
SET SPLVT=vt_organisme
SET SPLSQL="CREATE VIRTUAL TABLE '%SPLVT%' USING VirtualText('%GLSHPINPATH%\%CSV%.csv', '%GLCSVINCODE%', 1, COMMA, %GLCSVINQUOTE%, '%GLCSVINDELIM%');"
IF EXIST "%GLSHPINPATH%\%CSV%.csv" %GLSPLEX% "%GLCTDBSPL%" %SPLSQL%

SET CSV=t_reference
SET SPLVT=vt_reference
SET SPLSQL="CREATE VIRTUAL TABLE '%SPLVT%' USING VirtualText('%GLSHPINPATH%\%CSV%.csv', '%GLCSVINCODE%', 1, COMMA, %GLCSVINQUOTE%, '%GLCSVINDELIM%');"
IF EXIST "%GLSHPINPATH%\%CSV%.csv" %GLSPLEX% "%GLCTDBSPL%" %SPLSQL%

SET CSV=t_sitetech
SET SPLVT=vt_sitetech
SET SPLSQL="CREATE VIRTUAL TABLE '%SPLVT%' USING VirtualText('%GLSHPINPATH%\%CSV%.csv', '%GLCSVINCODE%', 1, COMMA, %GLCSVINQUOTE%, '%GLCSVINDELIM%');"
IF EXIST "%GLSHPINPATH%\%CSV%.csv" %GLSPLEX% "%GLCTDBSPL%" %SPLSQL%

SET CSV=t_ltech
SET SPLVT=vt_ltech
SET SPLSQL="CREATE VIRTUAL TABLE '%SPLVT%' USING VirtualText('%GLSHPINPATH%\%CSV%.csv', '%GLCSVINCODE%', 1, COMMA, %GLCSVINQUOTE%, '%GLCSVINDELIM%');"
IF EXIST "%GLSHPINPATH%\%CSV%.csv" %GLSPLEX% "%GLCTDBSPL%" %SPLSQL%

SET CSV=t_baie
SET SPLVT=vt_baie
SET SPLSQL="CREATE VIRTUAL TABLE '%SPLVT%' USING VirtualText('%GLSHPINPATH%\%CSV%.csv', '%GLCSVINCODE%', 1, COMMA, %GLCSVINQUOTE%, '%GLCSVINDELIM%');"
IF EXIST "%GLSHPINPATH%\%CSV%.csv" %GLSPLEX% "%GLCTDBSPL%" %SPLSQL%

SET CSV=t_tiroir
SET SPLVT=vt_tiroir
SET SPLSQL="CREATE VIRTUAL TABLE '%SPLVT%' USING VirtualText('%GLSHPINPATH%\%CSV%.csv', '%GLCSVINCODE%', 1, COMMA, %GLCSVINQUOTE%, '%GLCSVINDELIM%');"
IF EXIST "%GLSHPINPATH%\%CSV%.csv" %GLSPLEX% "%GLCTDBSPL%" %SPLSQL%

SET CSV=t_equipement
SET SPLVT=vt_equipement
SET SPLSQL="CREATE VIRTUAL TABLE '%SPLVT%' USING VirtualText('%GLSHPINPATH%\%CSV%.csv', '%GLCSVINCODE%', 1, COMMA, %GLCSVINQUOTE%, '%GLCSVINDELIM%');"
IF EXIST "%GLSHPINPATH%\%CSV%.csv" %GLSPLEX% "%GLCTDBSPL%" %SPLSQL%

SET CSV=t_suf
SET SPLVT=vt_suf
SET SPLSQL="CREATE VIRTUAL TABLE '%SPLVT%' USING VirtualText('%GLSHPINPATH%\%CSV%.csv', '%GLCSVINCODE%', 1, COMMA, %GLCSVINQUOTE%, '%GLCSVINDELIM%');"
IF EXIST "%GLSHPINPATH%\%CSV%.csv" %GLSPLEX% "%GLCTDBSPL%" %SPLSQL%

SET CSV=t_ptech
SET SPLVT=vt_ptech
SET SPLSQL="CREATE VIRTUAL TABLE '%SPLVT%' USING VirtualText('%GLSHPINPATH%\%CSV%.csv', '%GLCSVINCODE%', 1, COMMA, %GLCSVINQUOTE%, '%GLCSVINDELIM%');"
IF EXIST "%GLSHPINPATH%\%CSV%.csv" %GLSPLEX% "%GLCTDBSPL%" %SPLSQL%

SET CSV=t_ebp
SET SPLVT=vt_ebp
SET SPLSQL="CREATE VIRTUAL TABLE '%SPLVT%' USING VirtualText('%GLSHPINPATH%\%CSV%.csv', '%GLCSVINCODE%', 1, COMMA, %GLCSVINQUOTE%, '%GLCSVINDELIM%');"
IF EXIST "%GLSHPINPATH%\%CSV%.csv" %GLSPLEX% "%GLCTDBSPL%" %SPLSQL%

SET CSV=t_cassette
SET SPLVT=vt_cassette
SET SPLSQL="CREATE VIRTUAL TABLE '%SPLVT%' USING VirtualText('%GLSHPINPATH%\%CSV%.csv', '%GLCSVINCODE%', 1, COMMA, %GLCSVINQUOTE%, '%GLCSVINDELIM%');"
IF EXIST "%GLSHPINPATH%\%CSV%.csv" %GLSPLEX% "%GLCTDBSPL%" %SPLSQL%

SET CSV=t_conduite
SET SPLVT=vt_conduite
SET SPLSQL="CREATE VIRTUAL TABLE '%SPLVT%' USING VirtualText('%GLSHPINPATH%\%CSV%.csv', '%GLCSVINCODE%', 1, COMMA, %GLCSVINQUOTE%, '%GLCSVINDELIM%');"
IF EXIST "%GLSHPINPATH%\%CSV%.csv" %GLSPLEX% "%GLCTDBSPL%" %SPLSQL%

SET CSV=t_cond_chem
SET SPLVT=vt_cond_chem
SET SPLSQL="CREATE VIRTUAL TABLE '%SPLVT%' USING VirtualText('%GLSHPINPATH%\%CSV%.csv', '%GLCSVINCODE%', 1, COMMA, %GLCSVINQUOTE%, '%GLCSVINDELIM%');"
IF EXIST "%GLSHPINPATH%\%CSV%.csv" %GLSPLEX% "%GLCTDBSPL%" %SPLSQL%

SET CSV=t_masque
SET SPLVT=vt_masque
SET SPLSQL="CREATE VIRTUAL TABLE '%SPLVT%' USING VirtualText('%GLSHPINPATH%\%CSV%.csv', '%GLCSVINCODE%', 1, COMMA, %GLCSVINQUOTE%, '%GLCSVINDELIM%');"
IF EXIST "%GLSHPINPATH%\%CSV%.csv" %GLSPLEX% "%GLCTDBSPL%" %SPLSQL%

SET CSV=t_cab_cond
SET SPLVT=vt_cab_cond
SET SPLSQL="CREATE VIRTUAL TABLE '%SPLVT%' USING VirtualText('%GLSHPINPATH%\%CSV%.csv', '%GLCSVINCODE%', 1, COMMA, %GLCSVINQUOTE%, '%GLCSVINDELIM%');"
IF EXIST "%GLSHPINPATH%\%CSV%.csv" %GLSPLEX% "%GLCTDBSPL%" %SPLSQL%

SET CSV=t_love
SET SPLVT=vt_love
SET SPLSQL="CREATE VIRTUAL TABLE '%SPLVT%' USING VirtualText('%GLSHPINPATH%\%CSV%.csv', '%GLCSVINCODE%', 1, COMMA, %GLCSVINQUOTE%, '%GLCSVINDELIM%');"
IF EXIST "%GLSHPINPATH%\%CSV%.csv" %GLSPLEX% "%GLCTDBSPL%" %SPLSQL%

SET CSV=t_fibre
SET SPLVT=vt_fibre
SET SPLSQL="CREATE VIRTUAL TABLE '%SPLVT%' USING VirtualText('%GLSHPINPATH%\%CSV%.csv', '%GLCSVINCODE%', 1, COMMA, %GLCSVINQUOTE%, '%GLCSVINDELIM%');"
IF EXIST "%GLSHPINPATH%\%CSV%.csv" %GLSPLEX% "%GLCTDBSPL%" %SPLSQL%

SET CSV=t_position
SET SPLVT=vt_position
SET SPLSQL="CREATE VIRTUAL TABLE '%SPLVT%' USING VirtualText('%GLSHPINPATH%\%CSV%.csv', '%GLCSVINCODE%', 1, COMMA, %GLCSVINQUOTE%, '%GLCSVINDELIM%');"
IF EXIST "%GLSHPINPATH%\%CSV%.csv" %GLSPLEX% "%GLCTDBSPL%" %SPLSQL%

SET CSV=t_ropt
SET SPLVT=vt_ropt
SET SPLSQL="CREATE VIRTUAL TABLE '%SPLVT%' USING VirtualText('%GLSHPINPATH%\%CSV%.csv', '%GLCSVINCODE%', 1, COMMA, %GLCSVINQUOTE%, '%GLCSVINDELIM%');"
IF EXIST "%GLSHPINPATH%\%CSV%.csv" %GLSPLEX% "%GLCTDBSPL%" %SPLSQL%

SET CSV=t_siteemission
SET SPLVT=vt_siteemission
SET SPLSQL="CREATE VIRTUAL TABLE '%SPLVT%' USING VirtualText('%GLSHPINPATH%\%CSV%.csv', '%GLCSVINCODE%', 1, COMMA, %GLCSVINQUOTE%, '%GLCSVINDELIM%');"
IF EXIST "%GLSHPINPATH%\%CSV%.csv" %GLSPLEX% "%GLCTDBSPL%" %SPLSQL%

SET CSV=t_document
SET SPLVT=vt_document
SET SPLSQL="CREATE VIRTUAL TABLE '%SPLVT%' USING VirtualText('%GLSHPINPATH%\%CSV%.csv', '%GLCSVINCODE%', 1, COMMA, %GLCSVINQUOTE%, '%GLCSVINDELIM%');"
IF EXIST "%GLSHPINPATH%\%CSV%.csv" %GLSPLEX% "%GLCTDBSPL%" %SPLSQL%

SET CSV=t_docobj
SET SPLVT=vt_docobj
SET SPLSQL="CREATE VIRTUAL TABLE '%SPLVT%' USING VirtualText('%GLSHPINPATH%\%CSV%.csv', '%GLCSVINCODE%', 1, COMMA, %GLCSVINQUOTE%, '%GLCSVINDELIM%');"
IF EXIST "%GLSHPINPATH%\%CSV%.csv" %GLSPLEX% "%GLCTDBSPL%" %SPLSQL%

ECHO FIN DE CONNEXION DES CSV (TABLES vt_)
GOTO:EOF

PAUSE
